//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Centre_de_formation
{
    using System;
    using System.Collections.Generic;
    
    public partial class groupe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public groupe()
        {
            this.Stagaire = new HashSet<Stagaire>();
        }
    
        public int id_gp { get; set; }
        public string intitule { get; set; }
        public Nullable<int> id_As { get; set; }
        public Nullable<int> id_br { get; set; }
        public Nullable<int> id_nv { get; set; }
    
        public virtual Annescolaire Annescolaire { get; set; }
        public virtual branche branche { get; set; }
        public virtual niveau niveau { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stagaire> Stagaire { get; set; }
    }
}
