//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Centre_de_formation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gestion_EcoleEntities4 : DbContext
    {
        public Gestion_EcoleEntities4()
            : base("name=Gestion_EcoleEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Annescolaire> Annescolaire { get; set; }
        public virtual DbSet<branche> branche { get; set; }
        public virtual DbSet<Evaluation> Evaluation { get; set; }
        public virtual DbSet<Exam> Exam { get; set; }
        public virtual DbSet<groupe> groupe { get; set; }
        public virtual DbSet<Matiere> Matiere { get; set; }
        public virtual DbSet<niveau> niveau { get; set; }
        public virtual DbSet<Stagaire> Stagaire { get; set; }
    }
}
