//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Centre_de_formation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stagaire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stagaire()
        {
            this.Evaluation = new HashSet<Evaluation>();
        }
    
        public int n_ins { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public Nullable<System.DateTime> Date_naissance { get; set; }
        public string Nom_Ar { get; set; }
        public string Prenom_Ar { get; set; }
        public string Cin { get; set; }
        public string Niveau_scolaire { get; set; }
        public string adresse { get; set; }
        public Nullable<int> tel { get; set; }
        public Nullable<int> id_gp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluation> Evaluation { get; set; }
        public virtual groupe groupe { get; set; }
    }
}
